/**
 * This class is generated by jOOQ
 */
package tech.codingclub.helix;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in public
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table public.coders
	 */
	public static final tech.codingclub.helix.tables.Coders CODERS = tech.codingclub.helix.tables.Coders.CODERS;

	/**
	 * The table public.follower
	 */
	public static final tech.codingclub.helix.tables.Follower FOLLOWER = tech.codingclub.helix.tables.Follower.FOLLOWER;

	/**
	 * The table public.members
	 */
	public static final tech.codingclub.helix.tables.Members MEMBERS = tech.codingclub.helix.tables.Members.MEMBERS;

	/**
	 * The table public.tweet
	 */
	public static final tech.codingclub.helix.tables.Tweet TWEET = tech.codingclub.helix.tables.Tweet.TWEET;
}
